### ISSUE TITLE
GNURadio 3.8 support

### ISSUE THREAD

**Issue by ra1nb0w** [daniestevez/gr-linrad#1]
Hi,
do you think to support gnuradio 3.8?
thank you

**Comment by daniestevez** [comment]
Hi,

I ported my main GNU Radio project, gr-satellites, to 3.8, but I haven't ported the smaller ones to 3.8 yet. It should be quick and straightforward, but I haven't set to do it yet (always busy with other things). Maybe it would be good to force myself and port all in one go soon (we have some holidays in Spain now, so it could actually happen).

In any case I'll leave this issue open as a reminder until I get all those OOT's ported.

**Comment by ra1nb0w** [comment]
Thank you ;-)

**Comment by daniestevez** [comment]
This is done and tested now.

**Comment by ra1nb0w** [comment]
thank you very much!
